parameters:
  - name: 'jobName'
    type: string
  - name: 'clusterServiceConnection' #Kubernetes Service Connection name
    type: string
  - name: 'containerRegistry'
    type: string
  - name: 'namespace'
    type: string
  - name: 'secretName'
    type: string
jobs:
  - job: ${{ parameters.jobName }}
    steps:
      - checkout: none
      - task: KubernetesManifest@0
        inputs:
          action: 'createSecret'
          kubernetesServiceConnection: '${{ parameters.clusterServiceConnection }}'
          namespace: '${{ parameters.namespace }}'
          secretType: 'dockerRegistry'
          secretName: '${{ parameters.secretName }}'
          dockerRegistryEndpoint: '${{ parameters.containerRegistry }}'
        displayName: Create ImagePullSecret
