parameters:
  - name: 'jobName'
    type: string
  - name: 'nodeVersion'
    type: string
jobs:
  - job: ${{ parameters.jobName }}
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '${{ parameters.nodeVersion }}'
        displayName: 'Install Node.js'

      - script: npm ci
        displayName: npm ci
      
      - script: npm run-script build
        displayName: npm build
      
      - script: |
          npm test -- --watchAll=false
          find
        displayName: npm test

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.Repository.LocalPath)/build/'
          artifact: 'static'
          publishLocation: 'pipeline'